# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/planify
spring.datasource.username=postgres
spring.datasource.password=Bogdan.1972lrvxi
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=

# Dezactivez open-in-view
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=4b6250655368566d597133743677397a244326462948404d6251655468576d5a
app.jwt.expiration-ms=86400000

# Upload poze
app.upload.dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB
