export const facilityLabels: Record<string, string> = {
    PET_FRIENDLY: 'Pet Friendly',
    TERRACE: 'Terasă',
    PARKING: 'Parcare',
    AIR_CONDITIONING: 'Aer Condiționat',
    WIFI: 'WiFi',
    POOL: 'Piscină',
    LIVE_MUSIC: 'Muzică Live',
    PROJECTOR: 'Proiector',
    PRIVATE_ROOM: 'Cameră Privată',
    WHEELCHAIR_ACCESSIBLE: 'Acces Cărucioare',
    HEATED_TERRACE: 'Terasă Încălzită',
    SMOKING_AREA: 'Zonă Fumat',
    NON_SMOKING_AREA: 'Zonă Nefumători',
    KIDS_PLAY_AREA: 'Spațiu Copii',
    HIGH_CHAIRS: 'Scaune Înalte',
    BOARD_GAMES: 'Jocuri de Societate',
    KARAOKE: 'Karaoke',
    BILLIARDS: 'Biliard',
    DANCE_FLOOR: 'Pistă Dans',
    POWER_OUTLETS: 'Prize',
    COWORKING_FRIENDLY: 'Coworking',
    VALET_PARKING: 'Valet Parking',
    BIKE_PARKING: 'Parcare Biciclete',
    EV_CHARGING: 'Încărcare Mașini Electrice',
    ROOFTOP: 'Rooftop',
    GARDEN: 'Grădină',
    COAT_CHECK: 'Garderobă',
    CARD_PAYMENT: 'Plată Card',
    CASH_ONLY: 'Doar Numerar',
    FIREPLACE: 'Șemineu',
    WATERFRONT: 'Pe Malul Apei',
    PANORAMIC_VIEW: 'Priveliște Panoramică',
    VIP_LOUNGE: 'Zonă VIP',
    SHISHA: 'Narghilea',
    SPORTS_TV: 'TV Sporturi',
    DJ_BOOTH: 'DJ',
    FOOSBALL: 'Fotbal de Masă',
    ARCADE_GAMES: 'Jocuri Arcade',
    OPEN_KITCHEN: 'Bucătărie Deschisă',
    CRAFT_BEER_ON_TAP: 'Bere Artizanală',
    SPECIALTY_COFFEE: 'Cafea de Specialitate',
    STAGE: 'Scenă',
    SOUND_SYSTEM: 'Sistem Audio',
    MICROPHONE: 'Microfon',
    PHOTOBOOTH: 'Cabină Foto',
};

export const typeLabels: Record<string, string> = {
    RESTAURANT: 'Restaurant',
    BAR: 'Bar',
    CLUB: 'Club',
    WORK_HUB: 'Work Hub',
    GARDEN: 'Grădină',
    ROOFTOP: 'Rooftop',
    CAFE: 'Cafenea',
    BISTRO: 'Bistro',
    TEA_HOUSE: 'Ceainărie',
    PUB: 'Pub',
    LOUNGE: 'Lounge',
    WINE_BAR: 'Wine Bar',
    SPEAKEASY: 'Speakeasy',
    PIZZERIA: 'Pizzerie',
    FAST_FOOD: 'Fast Food',
    DINER: 'Diner',
    EVENT_VENUE: 'Sală Evenimente',
    FOOD_HALL: 'Food Hall',
};

export function formatTime(time: string): string {
    return time.substring(0, 5);
}

export function cn(...classes: (string | undefined | null | false)[]): string {
    return classes.filter(Boolean).join(' ');
}